# Default application configuration
spring:
  application:
    name: sqs-pub-sub-demo

aws:
  region: us-east-1 # Override with AWS_REGION env variable
  access-key: ${AWS_ACCESS_KEY_ID:}
  secret-key: ${AWS_SECRET_ACCESS_KEY:}
  sqs:
    queue-url: ${AWS_SQS_QUEUE_URL:}
